# Generated by Django 5.2.14 on 2026-05-19 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_mfaverificationtoken_totpdevice_backupcode"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="user",
            unique_together=set(),
        ),
    ]
