# Generated by Django 5.2.14 on 2026-05-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenantconfiguration_tenant_conf_tenant__216c25_idx"),
        ("users", "0010_rls_policies"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="apikey",
            index=models.Index(fields=["tenant"], name="api_keys_tenant__54d768_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["tenant"], name="audit_logs_tenant__e4709b_idx"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["tenant"], name="user_sessio_tenant__21e332_idx"
            ),
        ),
    ]
