# Generated by Django 5.2.14 on 2026-05-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenantconfiguration_tenant_conf_tenant__216c25_idx"),
        ("users", "0011_apikey_api_keys_tenant__54d768_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="audit_logs_action_31f574_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["created_at"], name="audit_logs_created_262184_idx"
            ),
        ),
    ]
