# Generated by Django 5.2.14 on 2026-06-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
