# Generated by Django 5.2.14 on 2026-06-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_tenant_plan_tier'),
        ('users', '0014_user_profile_picture_key'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usersession',
            name='user_sessio_session_e62ba3_idx',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='session_id',
        ),
        migrations.AddField(
            model_name='usersession',
            name='current_refresh_jti',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersession',
            name='revoked_reason',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['current_refresh_jti'], name='user_sessio_current_94cb91_idx'),
        ),
    ]
