# Generated by Django 5.2.14 on 2026-05-23 06:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_tenantconfiguration_tenant_conf_tenant__216c25_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_pattern', models.TextField(help_text='Regex pattern matched against incoming log error messages.')),
                ('instructions', models.TextField(help_text="Runbook steps injected into the AI agent's analysis prompt when this pattern matches.")),
                ('source_version', models.BigIntegerField(default=1, help_text='Auto-incremented on every save; used by snapshot consumers to reject stale events.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='tenants.tenant')),
            ],
            options={
                'db_table': 'playbooks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant'], name='playbooks_tenant__716c48_idx')],
            },
        ),
    ]
