# Generated by Django 5.2.14 on 2026-06-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_tenantconfiguration_tenant_conf_tenant__216c25_idx"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tenant",
            old_name="stripe_customer_id",
            new_name="razorpay_customer_id",
        ),
        migrations.AddField(
            model_name="tenant",
            name="razorpay_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
