# Generated by Django 5.2.14 on 2026-06-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenants",
            "0004_rename_stripe_customer_id_tenant_razorpay_customer_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="plan_tier",
            field=models.CharField(
                choices=[("free", "Free"), ("pro", "Pro"), ("max", "Max")],
                default="free",
                max_length=20,
            ),
        ),
    ]
