# Generated by Django 5.2.14 on 2026-05-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='githubintegration',
            new_name='github_inte_tenant__e7144b_idx',
            old_name='gh_integ_tenant_idx',
        ),
        migrations.RenameIndex(
            model_name='githubintegration',
            new_name='github_inte_indexin_ed7904_idx',
            old_name='gh_integ_status_idx',
        ),
        migrations.AlterField(
            model_name='githubintegration',
            name='default_branch',
            field=models.CharField(default='main', help_text='Branch that is indexed and monitored for push events.', max_length=255),
        ),
        migrations.AlterField(
            model_name='githubintegration',
            name='encrypted_pat',
            field=models.TextField(help_text='Fernet-encrypted GitHub Personal Access Token. Use integrations.encryption.decrypt_secret() to read at runtime.'),
        ),
        migrations.AlterField(
            model_name='githubintegration',
            name='indexing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('indexing', 'Indexing'), ('indexed', 'Indexed'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current state of the AST code-indexing pipeline for this repository.', max_length=20),
        ),
        migrations.AlterField(
            model_name='githubintegration',
            name='last_indexed_commit',
            field=models.CharField(blank=True, help_text='SHA of the last successfully indexed commit. Null until first index.', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='githubintegration',
            name='repo_name',
            field=models.CharField(help_text='Repository name (without the owner prefix).', max_length=255),
        ),
        migrations.AlterField(
            model_name='githubintegration',
            name='repo_owner',
            field=models.CharField(help_text='GitHub organisation or user name that owns the repository.', max_length=255),
        ),
        migrations.AlterField(
            model_name='githubintegration',
            name='repo_url',
            field=models.URLField(help_text='Full HTTPS clone URL, e.g. https://github.com/my-org/my-repo', max_length=500),
        ),
        migrations.AlterField(
            model_name='githubintegration',
            name='source_version',
            field=models.BigIntegerField(default=1, help_text="Monotonically-increasing counter. Incremented on every save. FastAPI's snapshot consumer discards events with a source_version <= the current snapshot row's version."),
        ),
        migrations.AlterField(
            model_name='githubintegration',
            name='webhook_id',
            field=models.CharField(blank=True, help_text='GitHub webhook ID returned after webhook registration. Null until registered.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='githubintegration',
            name='webhook_secret',
            field=models.TextField(help_text='Fernet-encrypted webhook secret used to validate incoming push events. Use integrations.encryption.decrypt_secret() to read at runtime.'),
        ),
    ]
