# Generated by Django 5.2.14 on 2026-06-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "integrations",
            "0002_rename_gh_integ_tenant_idx_github_inte_tenant__e7144b_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="githubintegration",
            name="encrypted_pat",
        ),
        migrations.RemoveField(
            model_name="githubintegration",
            name="webhook_secret",
        ),
        migrations.AddField(
            model_name="githubintegration",
            name="github_installation_id",
            field=models.CharField(
                default="",
                help_text="The GitHub App installation ID used to authenticate and fetch tokens.",
                max_length=255,
            ),
        ),
    ]
