# Generated by Django 5.2.14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "integrations",
            "0003_remove_githubintegration_encrypted_pat_and_more",
        ),
        (
            "tenants",
            "0003_tenantconfiguration_tenant_conf_tenant__216c25_idx", # From 0001
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubintegration",
            name="tenant",
            field=models.ForeignKey(
                help_text="The tenant this GitHub integration belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="github_integrations",
                to="tenants.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="githubintegration",
            unique_together={("tenant", "repo_url")},
        ),
    ]
