# Generated by Django 5.2.14 on 2026-07-07 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_multi_repo_per_tenant"),
        ("tenants", "0005_alter_tenant_plan_tier"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRepoMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        help_text="The service_name sent by the SDK (e.g. 'payment-api').",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "github_integration",
                    models.ForeignKey(
                        help_text="The repository to map this service to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_mappings",
                        to="integrations.githubintegration",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="The tenant this mapping belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_mappings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "service_repo_mappings",
                "indexes": [
                    models.Index(
                        fields=["tenant", "service_name"],
                        name="service_rep_tenant__d072c3_idx",
                    )
                ],
                "unique_together": {("tenant", "service_name")},
            },
        ),
    ]
