"""add_github_columns_to_tenant_snapshot

Revision ID: 0003
Revises: 0002
Create Date: 2026-05-27 09:00:03.873705+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_log_summaries_level", table_name="log_summaries")
    op.drop_index("ix_log_summaries_service_name", table_name="log_summaries")
    op.drop_index("ix_log_summaries_tenant_id", table_name="log_summaries")
    op.drop_index("ix_log_summaries_tenant_level", table_name="log_summaries")
    op.drop_index("ix_log_summaries_tenant_timestamp", table_name="log_summaries")
    op.drop_index("ix_log_summaries_timestamp", table_name="log_summaries")
    op.drop_table("log_summaries")
    op.drop_index(
        "ix_ingested_log_metadata_created_at", table_name="ingested_log_metadata"
    )
    op.drop_index(
        "ix_ingested_log_metadata_tenant_id", table_name="ingested_log_metadata"
    )
    op.drop_table("ingested_log_metadata")
    op.alter_column(
        "alert_rule_snapshots",
        "severity_filter",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        comment="Only alert on these severity levels e.g. ['critical','high'].",
        existing_nullable=True,
    )
    op.alter_column(
        "alert_rule_snapshots",
        "recipient_ids",
        existing_type=postgresql.ARRAY(sa.UUID()),
        comment="UUIDs of users who should receive this alert.",
        existing_nullable=True,
    )
    op.alter_column(
        "outbox",
        "key",
        existing_type=sa.VARCHAR(length=256),
        comment="Kafka message key (e.g. tenant_id or incident_id). Determines partition assignment for ordered delivery.",
        existing_comment="Kafka message key (e.g. tenant_id or incident_id).",
        existing_nullable=False,
    )
    op.alter_column(
        "outbox",
        "payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Event payload. Must include event_id, event_type, source_version.",
        existing_comment="Event payload including envelope fields.",
        existing_nullable=False,
    )
    op.alter_column(
        "outbox",
        "published",
        existing_type=sa.BOOLEAN(),
        comment="Set to true by Debezium after the row has been published to Kafka. Rows with published=false older than 1 hour indicate a CDC lag issue.",
        existing_comment="Set to true by Debezium after Kafka delivery.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.drop_index("ix_outbox_created_at", table_name="outbox")
    op.drop_index("ix_outbox_published", table_name="outbox")
    op.drop_index("ix_outbox_topic", table_name="outbox")
    op.alter_column(
        "playbook_snapshots",
        "error_pattern",
        existing_type=sa.TEXT(),
        comment="Regex pattern matched against log error messages.",
        existing_nullable=True,
    )
    op.alter_column(
        "playbook_snapshots",
        "instructions",
        existing_type=sa.TEXT(),
        comment="Runbook instructions injected into the AI agent's analysis prompt.",
        existing_nullable=True,
    )
    op.add_column(
        "tenant_snapshots",
        sa.Column(
            "github_repo_url",
            sa.Text(),
            nullable=True,
            comment="Full HTTPS clone URL of the connected repository.",
        ),
    )
    op.add_column(
        "tenant_snapshots",
        sa.Column(
            "github_repo_owner",
            sa.String(length=255),
            nullable=True,
            comment="GitHub organisation or user name that owns the repository.",
        ),
    )
    op.add_column(
        "tenant_snapshots",
        sa.Column(
            "github_repo_name",
            sa.String(length=255),
            nullable=True,
            comment="Repository name (without the owner prefix).",
        ),
    )
    op.add_column(
        "tenant_snapshots",
        sa.Column(
            "encrypted_github_pat",
            sa.Text(),
            nullable=True,
            comment="Fernet-encrypted GitHub Personal Access Token. Decrypt with the shared FERNET_ENCRYPTION_KEY at runtime. NEVER log or expose this value.",
        ),
    )
    op.add_column(
        "tenant_snapshots",
        sa.Column(
            "github_webhook_secret",
            sa.Text(),
            nullable=True,
            comment="Fernet-encrypted webhook signing secret. Used to validate incoming push events from GitHub.",
        ),
    )
    op.add_column(
        "tenant_snapshots",
        sa.Column(
            "github_default_branch",
            sa.String(length=255),
            nullable=True,
            comment="Branch that is indexed and monitored for push events.",
        ),
    )
    op.add_column(
        "tenant_snapshots",
        sa.Column(
            "github_indexing_status",
            sa.String(length=20),
            nullable=True,
            comment="Current AST indexing lifecycle state: pending | indexing | indexed | failed.",
        ),
    )
    op.add_column(
        "tenant_snapshots",
        sa.Column(
            "github_last_indexed_commit",
            sa.String(length=40),
            nullable=True,
            comment="SHA of the last successfully indexed commit.",
        ),
    )
    op.alter_column(
        "tenant_snapshots",
        "plan_tier",
        existing_type=sa.VARCHAR(length=32),
        comment="Billing plan tier: standard | professional | enterprise.",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_snapshots",
        "vector_namespace",
        existing_type=sa.VARCHAR(length=64),
        comment="Isolated pgvector namespace for this tenant.",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_snapshots",
        "kafka_group_id",
        existing_type=sa.VARCHAR(length=128),
        comment="Kafka consumer group assigned to this tenant.",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_snapshots",
        "is_suspended",
        existing_type=sa.BOOLEAN(),
        comment="Eventual-consistent suspension flag. Always verify against the Redis key tenant:{id}:suspended first.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "tenant_snapshots",
        "source_version",
        existing_type=sa.BIGINT(),
        comment="Source entity version from DB-1 — used to reject stale events.",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_snapshots",
        "synced_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp of the last successful snapshot upsert.",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tenant_snapshots",
        "synced_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment=None,
        existing_comment="Timestamp of the last successful snapshot upsert.",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "tenant_snapshots",
        "source_version",
        existing_type=sa.BIGINT(),
        comment=None,
        existing_comment="Source entity version from DB-1 — used to reject stale events.",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_snapshots",
        "is_suspended",
        existing_type=sa.BOOLEAN(),
        comment=None,
        existing_comment="Eventual-consistent suspension flag. Always verify against the Redis key tenant:{id}:suspended first.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "tenant_snapshots",
        "kafka_group_id",
        existing_type=sa.VARCHAR(length=128),
        comment=None,
        existing_comment="Kafka consumer group assigned to this tenant.",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_snapshots",
        "vector_namespace",
        existing_type=sa.VARCHAR(length=64),
        comment=None,
        existing_comment="Isolated pgvector namespace for this tenant.",
        existing_nullable=True,
    )
    op.alter_column(
        "tenant_snapshots",
        "plan_tier",
        existing_type=sa.VARCHAR(length=32),
        comment=None,
        existing_comment="Billing plan tier: standard | professional | enterprise.",
        existing_nullable=True,
    )
    op.drop_column("tenant_snapshots", "github_last_indexed_commit")
    op.drop_column("tenant_snapshots", "github_indexing_status")
    op.drop_column("tenant_snapshots", "github_default_branch")
    op.drop_column("tenant_snapshots", "github_webhook_secret")
    op.drop_column("tenant_snapshots", "encrypted_github_pat")
    op.drop_column("tenant_snapshots", "github_repo_name")
    op.drop_column("tenant_snapshots", "github_repo_owner")
    op.drop_column("tenant_snapshots", "github_repo_url")
    op.alter_column(
        "playbook_snapshots",
        "instructions",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Runbook instructions injected into the AI agent's analysis prompt.",
        existing_nullable=True,
    )
    op.alter_column(
        "playbook_snapshots",
        "error_pattern",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Regex pattern matched against log error messages.",
        existing_nullable=True,
    )
    op.create_index("ix_outbox_topic", "outbox", ["topic"], unique=False)
    op.create_index("ix_outbox_published", "outbox", ["published"], unique=False)
    op.create_index("ix_outbox_created_at", "outbox", ["created_at"], unique=False)
    op.alter_column(
        "outbox",
        "published",
        existing_type=sa.BOOLEAN(),
        comment="Set to true by Debezium after Kafka delivery.",
        existing_comment="Set to true by Debezium after the row has been published to Kafka. Rows with published=false older than 1 hour indicate a CDC lag issue.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "outbox",
        "payload",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Event payload including envelope fields.",
        existing_comment="Event payload. Must include event_id, event_type, source_version.",
        existing_nullable=False,
    )
    op.alter_column(
        "outbox",
        "key",
        existing_type=sa.VARCHAR(length=256),
        comment="Kafka message key (e.g. tenant_id or incident_id).",
        existing_comment="Kafka message key (e.g. tenant_id or incident_id). Determines partition assignment for ordered delivery.",
        existing_nullable=False,
    )
    op.alter_column(
        "alert_rule_snapshots",
        "recipient_ids",
        existing_type=postgresql.ARRAY(sa.UUID()),
        comment=None,
        existing_comment="UUIDs of users who should receive this alert.",
        existing_nullable=True,
    )
    op.alter_column(
        "alert_rule_snapshots",
        "severity_filter",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        comment=None,
        existing_comment="Only alert on these severity levels e.g. ['critical','high'].",
        existing_nullable=True,
    )
    op.create_table(
        "ingested_log_metadata",
        sa.Column(
            "incident_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
            comment="Client-supplied UUID for the crash event. Used as the S3 key suffix and Kafka message key.",
        ),
        sa.Column(
            "tenant_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
            comment="FK to tenant_snapshots; enforced by RLS policy.",
        ),
        sa.Column(
            "service_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="Name of the originating service from the SDK payload.",
        ),
        sa.Column(
            "environment",
            sa.VARCHAR(length=64),
            autoincrement=False,
            nullable=False,
            comment="Deployment environment label from the SDK payload.",
        ),
        sa.Column(
            "s3_path",
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            comment="S3 object key of the gzip-compressed context buffer. Format: logs/{tenant_id}/context/{incident_id}.json.gz",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
            comment="UTC timestamp recorded by the database at insert time.",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant_snapshots.tenant_id"],
            name="ingested_log_metadata_tenant_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("incident_id", name="ingested_log_metadata_pkey"),
    )
    op.create_index(
        "ix_ingested_log_metadata_tenant_id",
        "ingested_log_metadata",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_ingested_log_metadata_created_at",
        "ingested_log_metadata",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "log_summaries",
        sa.Column(
            "id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
            comment="Globally unique log summary identifier.",
        ),
        sa.Column(
            "tenant_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
            comment="Tenant that owns this log. Enforced via RLS policy.",
        ),
        sa.Column(
            "service_name",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="Name of the originating service.",
        ),
        sa.Column(
            "level",
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=False,
            comment="Log severity level: debug | info | warning | error | critical.",
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
            comment="Original timestamp of the log event as reported by the client.",
        ),
        sa.Column(
            "ingested_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
            comment="Server-side timestamp when the log was received by the ingest endpoint.",
        ),
        sa.PrimaryKeyConstraint("id", name="log_summaries_pkey"),
    )
    op.create_index(
        "ix_log_summaries_timestamp", "log_summaries", ["timestamp"], unique=False
    )
    op.create_index(
        "ix_log_summaries_tenant_timestamp",
        "log_summaries",
        ["tenant_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_log_summaries_tenant_level",
        "log_summaries",
        ["tenant_id", "level"],
        unique=False,
    )
    op.create_index(
        "ix_log_summaries_tenant_id", "log_summaries", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_log_summaries_service_name", "log_summaries", ["service_name"], unique=False
    )
    op.create_index("ix_log_summaries_level", "log_summaries", ["level"], unique=False)
    # ### end Alembic commands ###
