"""create_code_index_table

Revision ID: a51be1689124
Revises: 0003
Create Date: 2026-05-28 10:47:51.136421+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a51be1689124"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "code_index",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Globally unique row identifier."
        ),
        sa.Column(
            "tenant_id",
            sa.UUID(),
            nullable=False,
            comment="Owning tenant UUID.  Enforced at the database layer by the RLS policy attached via the after_create DDL event listener.",
        ),
        sa.Column(
            "repo_url",
            sa.Text(),
            nullable=False,
            comment="Full HTTPS clone URL of the connected repository.",
        ),
        sa.Column(
            "file_path",
            sa.Text(),
            nullable=False,
            comment="Relative path of the source file within the repository root, e.g. src/payment/charge_service.py",
        ),
        sa.Column(
            "symbol_name",
            sa.Text(),
            nullable=False,
            comment="Fully-qualified symbol name as extracted by the AST parser, e.g. ChargeService or ChargeService.charge",
        ),
        sa.Column(
            "chunk_type",
            sa.String(length=32),
            nullable=True,
            comment="Symbol kind: 'function' or 'class'.",
        ),
        sa.Column(
            "start_line",
            sa.Integer(),
            nullable=False,
            comment="1-based line number where this symbol definition begins.",
        ),
        sa.Column(
            "end_line",
            sa.Integer(),
            nullable=False,
            comment="1-based line number where this symbol definition ends (inclusive).",
        ),
        sa.Column(
            "calls",
            postgresql.ARRAY(sa.Text()),
            nullable=True,
            comment="Symbol names directly invoked inside this block, extracted by the AST parser.  External library calls are filtered out via the imports list before storage.",
        ),
        sa.Column(
            "called_by",
            postgresql.ARRAY(sa.Text()),
            nullable=True,
            comment="Reserved for future reverse call-graph population.  Written as an empty array by the indexer until Phase 4+ populates it.",
        ),
        sa.Column(
            "imports",
            postgresql.ARRAY(sa.Text()),
            nullable=True,
            comment="Module-level import statements visible to this symbol, used to distinguish project-internal calls from external library calls.",
        ),
        sa.Column(
            "s3_key",
            sa.Text(),
            nullable=False,
            comment="Full S3 object key of the raw source file.  Format: code/{tenant_id}/{repo_name}/{commit_sha}/{file_path}",
        ),
        sa.Column(
            "last_commit",
            sa.Text(),
            nullable=False,
            comment="40-character SHA of the commit at which this row was last indexed. Used by the incremental indexer to skip unchanged files.",
        ),
        sa.Column(
            "indexed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Server-side UTC timestamp of the most recent upsert.",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "repo_url",
            "file_path",
            "symbol_name",
            name="uq_code_index_tenant_repo_file_symbol",
        ),
    )
    op.create_index(
        "ix_code_index_tenant_filepath",
        "code_index",
        ["tenant_id", "file_path"],
        unique=False,
    )
    op.create_index(
        op.f("ix_code_index_tenant_id"), "code_index", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_code_index_tenant_repo_filepath",
        "code_index",
        ["tenant_id", "repo_url", "file_path"],
        unique=False,
    )
    op.create_index(
        "ix_code_index_tenant_symbol",
        "code_index",
        ["tenant_id", "symbol_name"],
        unique=False,
    )
    op.create_table(
        "ingested_log_metadata",
        sa.Column(
            "incident_id",
            sa.UUID(),
            nullable=False,
            comment="Client-supplied UUID for the crash event. Used as the S3 key suffix and Kafka message key.",
        ),
        sa.Column(
            "tenant_id",
            sa.UUID(),
            nullable=False,
            comment="FK to tenant_snapshots; enforced by RLS policy.",
        ),
        sa.Column(
            "service_name",
            sa.String(length=255),
            nullable=False,
            comment="Name of the originating service from the SDK payload.",
        ),
        sa.Column(
            "environment",
            sa.String(length=64),
            nullable=False,
            comment="Deployment environment label from the SDK payload.",
        ),
        sa.Column(
            "s3_path",
            sa.Text(),
            nullable=False,
            comment="S3 object key of the gzip-compressed context buffer. Format: logs/{tenant_id}/context/{incident_id}.json.gz",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="UTC timestamp recorded by the database at insert time.",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant_snapshots.tenant_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("incident_id"),
    )
    op.create_index(
        op.f("ix_ingested_log_metadata_tenant_id"),
        "ingested_log_metadata",
        ["tenant_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ingested_log_metadata_tenant_id"), table_name="ingested_log_metadata"
    )
    op.drop_table("ingested_log_metadata")
    op.drop_index("ix_code_index_tenant_symbol", table_name="code_index")
    op.drop_index("ix_code_index_tenant_repo_filepath", table_name="code_index")
    op.drop_index(op.f("ix_code_index_tenant_id"), table_name="code_index")
    op.drop_index("ix_code_index_tenant_filepath", table_name="code_index")
    op.drop_table("code_index")
    # ### end Alembic commands ###
