"""Add APIKeySnapshot

Revision ID: 281c388ff001
Revises: 2badda936ecb
Create Date: 2026-06-27 04:30:47.271170+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281c388ff001'
down_revision: Union[str, None] = '2badda936ecb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_snapshots',
    sa.Column('id', sa.UUID(), nullable=False, comment='Matches api_keys.id in DB-1.'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant this key belongs to.'),
    sa.Column('key', sa.String(length=255), nullable=False, comment='The actual raw API key token.'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the key can still be used.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_snapshots_key'), 'api_key_snapshots', ['key'], unique=True)
    op.create_index(op.f('ix_api_key_snapshots_tenant_id'), 'api_key_snapshots', ['tenant_id'], unique=False)
    op.alter_column('tenant_snapshots', 'github_installation_id',
               existing_type=sa.BIGINT(),
               comment='GitHub App installation ID assigned when tenant installs the NeuralOps GitHub App.',
               existing_comment='GitHub App installation ID assigned when tenant installs the NeuralOps GitHub App',
               existing_nullable=True)
    op.drop_index('ix_tenant_snapshots_installation_id', table_name='tenant_snapshots')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tenant_snapshots_installation_id', 'tenant_snapshots', ['github_installation_id'], unique=False)
    op.alter_column('tenant_snapshots', 'github_installation_id',
               existing_type=sa.BIGINT(),
               comment='GitHub App installation ID assigned when tenant installs the NeuralOps GitHub App',
               existing_comment='GitHub App installation ID assigned when tenant installs the NeuralOps GitHub App.',
               existing_nullable=True)
    op.drop_index(op.f('ix_api_key_snapshots_tenant_id'), table_name='api_key_snapshots')
    op.drop_index(op.f('ix_api_key_snapshots_key'), table_name='api_key_snapshots')
    op.drop_table('api_key_snapshots')
    # ### end Alembic commands ###
