"""standardize severity enum

Revision ID: 5fe1733c648b
Revises: 882de2a5b78e
Create Date: 2026-06-29 06:15:20.456258+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe1733c648b'
down_revision: Union[str, None] = '882de2a5b78e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE incidents SET severity = 'low' WHERE severity IN ('info', 'unknown')")
    
    op.alter_column('incidents', 'severity',
               existing_type=sa.VARCHAR(length=32),
               comment='Classified severity: critical | high | medium | low.',
               existing_comment='Classified severity: critical | high | medium | low | info | unknown.',
               existing_nullable=False,
               server_default=sa.text("'low'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incidents', 'severity',
               existing_type=sa.VARCHAR(length=32),
               comment='Classified severity: critical | high | medium | low | info | unknown.',
               existing_comment='Classified severity: critical | high | medium | low.',
               existing_nullable=False,
               existing_server_default=sa.text("'unknown'::character varying"))
    # ### end Alembic commands ###
