"""replace recipient_ids with destinations

Revision ID: f869418ea181
Revises: 281c388ff001
Create Date: 2026-06-29 05:00:08.565102+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f869418ea181'
down_revision: Union[str, None] = '281c388ff001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rule_snapshots', sa.Column('destinations', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="List of destination objects (e.g. {'type': 'user', 'id': 'uuid'})."))
    op.drop_column('alert_rule_snapshots', 'recipient_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rule_snapshots', sa.Column('recipient_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True, comment='UUIDs of users who should receive this alert.'))
    op.drop_column('alert_rule_snapshots', 'destinations')
    # ### end Alembic commands ###
