"""Add ServiceRepoMappingSnapshot

Revision ID: 0fcd2cd2d1e6
Revises: c4e5f6a7b8c9
Create Date: 2026-07-07 10:19:48.135564+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fcd2cd2d1e6'
down_revision: Union[str, None] = 'c4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_repo_mapping_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('repo_url', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_snapshots.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_repo_mapping_snapshots_tenant_id'), 'service_repo_mapping_snapshots', ['tenant_id'], unique=False)
    op.drop_index('ix_github_integration_snapshots_tenant_repo', table_name='github_integration_snapshots')
    op.alter_column('tenant_snapshots', 'github_repo_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Full HTTPS clone URL of the connected repository.',
               existing_nullable=True)
    op.alter_column('tenant_snapshots', 'github_repo_owner',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='GitHub organisation or user name that owns the repository.',
               existing_nullable=True)
    op.alter_column('tenant_snapshots', 'github_repo_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Repository name (without the owner prefix).',
               existing_nullable=True)
    op.alter_column('tenant_snapshots', 'github_installation_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='GitHub App installation ID assigned when tenant installs the NeuralOps GitHub App.',
               existing_nullable=True)
    op.alter_column('tenant_snapshots', 'github_default_branch',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Branch that is indexed and monitored for push events.',
               existing_nullable=True)
    op.alter_column('tenant_snapshots', 'github_indexing_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Current AST indexing lifecycle state: pending | indexing | indexed | failed.',
               existing_nullable=True)
    op.alter_column('tenant_snapshots', 'github_last_indexed_commit',
               existing_type=sa.VARCHAR(length=40),
               comment=None,
               existing_comment='SHA of the last successfully indexed commit.',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenant_snapshots', 'github_last_indexed_commit',
               existing_type=sa.VARCHAR(length=40),
               comment='SHA of the last successfully indexed commit.',
               existing_nullable=True)
    op.alter_column('tenant_snapshots', 'github_indexing_status',
               existing_type=sa.VARCHAR(length=20),
               comment='Current AST indexing lifecycle state: pending | indexing | indexed | failed.',
               existing_nullable=True)
    op.alter_column('tenant_snapshots', 'github_default_branch',
               existing_type=sa.VARCHAR(length=255),
               comment='Branch that is indexed and monitored for push events.',
               existing_nullable=True)
    op.alter_column('tenant_snapshots', 'github_installation_id',
               existing_type=sa.BIGINT(),
               comment='GitHub App installation ID assigned when tenant installs the NeuralOps GitHub App.',
               existing_nullable=True)
    op.alter_column('tenant_snapshots', 'github_repo_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Repository name (without the owner prefix).',
               existing_nullable=True)
    op.alter_column('tenant_snapshots', 'github_repo_owner',
               existing_type=sa.VARCHAR(length=255),
               comment='GitHub organisation or user name that owns the repository.',
               existing_nullable=True)
    op.alter_column('tenant_snapshots', 'github_repo_url',
               existing_type=sa.TEXT(),
               comment='Full HTTPS clone URL of the connected repository.',
               existing_nullable=True)
    op.create_index('ix_github_integration_snapshots_tenant_repo', 'github_integration_snapshots', ['tenant_id', 'repo_url'], unique=True)
    op.drop_index(op.f('ix_service_repo_mapping_snapshots_tenant_id'), table_name='service_repo_mapping_snapshots')
    op.drop_table('service_repo_mapping_snapshots')
    # ### end Alembic commands ###
