"""rename alert to notificationdelivery

Revision ID: 882de2a5b78e
Revises: f869418ea181
Create Date: 2026-06-29 06:02:13.337547+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '882de2a5b78e'
down_revision: Union[str, None] = 'f869418ea181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_deliveries',
    sa.Column('id', sa.UUID(), nullable=False, comment='Globally unique alert identifier.'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Owning tenant UUID — enforced via RLS policy.'),
    sa.Column('incident_id', sa.UUID(), nullable=False, comment='FK to the incident that triggered this alert.'),
    sa.Column('alert_rule_id', sa.UUID(), nullable=True, comment='FK to alert_rule_snapshots.rule_id. NULL if alert was dispatched manually.'),
    sa.Column('destination_type', sa.String(length=32), nullable=False, comment='Delivery type: in_app | email | pagerduty | slack.'),
    sa.Column('destination_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Snapshot of the destination config used (e.g. webhook URL or user ID).'),
    sa.Column('http_status_code', sa.Integer(), nullable=True, comment='HTTP status code from the external delivery attempt.'),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False, comment='Number of delivery attempts made.'),
    sa.Column('status', sa.String(length=32), server_default='pending', nullable=False, comment='Delivery status: pending | delivered | failed | skipped.'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if status=failed.'),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the notification was successfully dispatched.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation timestamp.'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='fk_notif_deliveries_incident_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_snapshots.tenant_id'], name='fk_notif_deliveries_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Phase 4 — Notification dispatch records.'
    )
    op.create_index('ix_notif_deliveries_status_pending', 'notification_deliveries', ['status', 'created_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_notif_deliveries_tenant_incident', 'notification_deliveries', ['tenant_id', 'incident_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_incident_id'), 'notification_deliveries', ['incident_id'], unique=False)
    op.create_index(op.f('ix_notification_deliveries_tenant_id'), 'notification_deliveries', ['tenant_id'], unique=False)
    op.drop_index('ix_alerts_incident_id', table_name='alerts')
    op.drop_index('ix_alerts_status_pending', table_name='alerts', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index('ix_alerts_tenant_id', table_name='alerts')
    op.drop_index('ix_alerts_tenant_incident', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False, comment='Globally unique alert identifier.'),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False, comment='Owning tenant UUID — enforced via RLS policy.'),
    sa.Column('incident_id', sa.UUID(), autoincrement=False, nullable=False, comment='FK to the incident that triggered this alert.'),
    sa.Column('alert_rule_id', sa.UUID(), autoincrement=False, nullable=True, comment='FK to alert_rule_snapshots.rule_id. NULL if alert was dispatched manually.'),
    sa.Column('channel', sa.VARCHAR(length=32), autoincrement=False, nullable=False, comment='Delivery channel: in_app | email | webhook.'),
    sa.Column('recipient_user_id', sa.UUID(), autoincrement=False, nullable=True, comment='UUID of the recipient user (from alert_rule_snapshots.recipient_ids).'),
    sa.Column('destination', sa.VARCHAR(length=512), autoincrement=False, nullable=True, comment='Email address or webhook URL for the delivery target.'),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False, comment='Delivery status: pending | delivered | failed | skipped.'),
    sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True, comment='Error message if status=failed.'),
    sa.Column('dispatched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Timestamp when the notification was successfully dispatched.'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Row creation timestamp.'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name='fk_alerts_incident_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant_snapshots.tenant_id'], name='fk_alerts_tenant_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='alerts_pkey'),
    comment='Phase 4 — Notification dispatch records.'
    )
    op.create_index('ix_alerts_tenant_incident', 'alerts', ['tenant_id', 'incident_id'], unique=False)
    op.create_index('ix_alerts_tenant_id', 'alerts', ['tenant_id'], unique=False)
    op.create_index('ix_alerts_status_pending', 'alerts', ['status', 'created_at'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.create_index('ix_alerts_incident_id', 'alerts', ['incident_id'], unique=False)
    op.drop_index(op.f('ix_notification_deliveries_tenant_id'), table_name='notification_deliveries')
    op.drop_index(op.f('ix_notification_deliveries_incident_id'), table_name='notification_deliveries')
    op.drop_index('ix_notif_deliveries_tenant_incident', table_name='notification_deliveries')
    op.drop_index('ix_notif_deliveries_status_pending', table_name='notification_deliveries', postgresql_where=sa.text("status = 'pending'"))
    op.drop_table('notification_deliveries')
    # ### end Alembic commands ###
