"""change assigned_user_id to assigned_user_ids array

Revision ID: 98fe46d10645
Revises: c8d4f3e0b2f5
Create Date: 2026-06-24 13:04:10.762362+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "98fe46d10645"
down_revision: Union[str, None] = "c8d4f3e0b2f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "playbook_embeddings_hnsw_idx",
        table_name="playbook_embeddings",
        postgresql_with={"m": "16", "ef_construction": "128"},
        postgresql_using="hnsw",
    )
    op.drop_index(
        "playbook_embeddings_playbook_id_idx", table_name="playbook_embeddings"
    )
    op.drop_index("playbook_embeddings_tenant_id_idx", table_name="playbook_embeddings")
    op.drop_index(
        "playbook_embeddings_tenant_id_source_version_idx",
        table_name="playbook_embeddings",
    )
    op.drop_table("playbook_embeddings")
    op.alter_column(
        "alerts",
        "alert_rule_id",
        existing_type=sa.UUID(),
        comment="FK to alert_rule_snapshots.rule_id. NULL if alert was dispatched manually.",
        existing_comment="UUID of the alert_rule_snapshot that triggered this alert. NULL if the alert was dispatched manually.",
        existing_nullable=True,
    )
    op.alter_column(
        "alerts",
        "recipient_user_id",
        existing_type=sa.UUID(),
        comment="UUID of the recipient user (from alert_rule_snapshots.recipient_ids).",
        existing_comment="UUID of the recipient user.",
        existing_nullable=True,
    )
    op.alter_column(
        "alerts",
        "failure_reason",
        existing_type=sa.TEXT(),
        comment="Error message if status=failed.",
        existing_comment="Error message populated when status=failed.",
        existing_nullable=True,
    )
    op.create_table_comment(
        "alerts",
        "Phase 4 — Notification dispatch records.",
        existing_comment=None,
        schema=None,
    )
    op.alter_column(
        "analyses",
        "incident_id",
        existing_type=sa.UUID(),
        comment="FK to incidents.id. One analysis per incident.",
        existing_comment="FK to incidents.id. One analysis per incident (1-to-1).",
        existing_nullable=False,
    )
    op.alter_column(
        "analyses",
        "total_latency_ms",
        existing_type=sa.INTEGER(),
        comment="Wall-clock ms from run_agent task start to DB commit.",
        existing_comment="Wall-clock milliseconds from run_agent task start to DB commit.",
        existing_nullable=True,
    )
    op.alter_column(
        "analyses",
        "node_results",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Per-node execution metadata keyed by node name. Keys: classifier, code_retriever, playbook_matcher, analyzer, fix_generator, confidence_scorer, action_decision. Each value contains latency_ms and node-specific fields.",
        existing_comment="Per-node execution metadata keyed by node name. Keys: classifier, code_retriever, playbook_matcher, analyzer, fix_generator, confidence_scorer, action_decision.",
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "analyses",
        "code_context_snapshot",
        existing_type=sa.TEXT(),
        comment="The exact code snippet text assembled by the CodeRetriever and passed to GPT-4. Stored for audit and replay.",
        existing_comment="The exact code snippet text assembled by the CodeRetriever and passed to GPT-4. Stored for audit and analysis replay.",
        existing_nullable=True,
    )
    op.alter_column(
        "analyses",
        "matched_playbook_id",
        existing_type=sa.UUID(),
        comment="UUID of the PlaybookSnapshot that matched this incident. NULL if no playbook matched.",
        existing_comment="UUID of the PlaybookSnapshot that matched this incident. NULL if no playbook pattern matched.",
        existing_nullable=True,
    )
    op.alter_column(
        "analyses",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when this analysis was persisted.",
        existing_comment="Timestamp when this analysis record was persisted.",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_table_comment(
        "analyses",
        "Phase 4 — LangGraph agent execution traces.",
        existing_comment=None,
        schema=None,
    )
    op.add_column(
        "incidents",
        sa.Column(
            "assigned_user_ids",
            postgresql.ARRAY(sa.UUID()),
            server_default="{}",
            nullable=False,
            comment="UUIDs of the assigned engineers",
        ),
    )
    op.alter_column(
        "incidents",
        "occurrence_count",
        existing_type=sa.INTEGER(),
        comment="Total number of times this fingerprint has been seen.",
        existing_comment="Total number of times this fingerprint has been observed.",
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.alter_column(
        "incidents",
        "occurrences",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        comment="S3 keys of all compressed context buffers for this incident. Format: logs/{tenant_id}/context/{incident_id}.json.gz",
        existing_comment="S3 object keys for all context buffers belonging to this incident. Format: logs/{tenant_id}/context/{incident_id}.json.gz",
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::text[]"),
    )
    op.alter_column(
        "incidents",
        "error_message",
        existing_type=sa.TEXT(),
        comment="Full error message string from the log entry.",
        existing_comment="Full error message string from the triggering log entry.",
        existing_nullable=True,
    )
    op.alter_column(
        "incidents",
        "status",
        existing_type=sa.VARCHAR(length=32),
        comment="Incident lifecycle status: open | investigating | resolved | closed | draft | duplicate.",
        existing_comment="Incident lifecycle status: open | investigating | resolved | draft | duplicate.",
        existing_nullable=False,
        existing_server_default=sa.text("'open'::character varying"),
    )
    op.alter_column(
        "incidents",
        "is_draft",
        existing_type=sa.BOOLEAN(),
        comment="True when confidence_score < tenant threshold. Draft incidents are stored but not published to Kafka.",
        existing_comment="True when confidence_score is below the tenant threshold. Draft incidents are stored but not published to Kafka.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "incidents",
        "source_log_id",
        existing_type=sa.UUID(),
        comment="incident_id from ingested_log_metadata that triggered this incident. Provides a link back to the original ingest event.",
        existing_comment="incident_id from ingested_log_metadata that triggered this incident. Provides traceability back to the original ingest event.",
        existing_nullable=True,
    )
    op.alter_column(
        "incidents",
        "resolved_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when status was set to resolved. Null if still open.",
        existing_comment="Timestamp when status transitioned to resolved. NULL if open.",
        existing_nullable=True,
    )
    op.alter_column(
        "incidents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Row creation timestamp.",
        existing_comment="Row creation timestamp (server-side).",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "incidents",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Last modification timestamp.",
        existing_comment="Last modification timestamp (server-side).",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        "uq_incidents_tenant_fingerprint_active",
        table_name="incidents",
        postgresql_where="((status)::text <> 'resolved'::text)",
    )
    op.drop_index("ix_incidents_tenant_severity", table_name="incidents")
    op.create_index(
        "ix_incidents_tenant_severity",
        "incidents",
        ["tenant_id", "severity", sa.text("created_at DESC")],
        unique=False,
    )
    op.create_table_comment(
        "incidents",
        "Phase 4 — AI incident records. One row per unique error identity.",
        existing_comment=None,
        schema=None,
    )
    op.drop_column("incidents", "assigned_user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "incidents",
        sa.Column(
            "assigned_user_id",
            sa.UUID(),
            autoincrement=False,
            nullable=True,
            comment="UUID of the assigned engineer (references users in DB-1).",
        ),
    )
    op.drop_table_comment(
        "incidents",
        existing_comment="Phase 4 — AI incident records. One row per unique error identity.",
        schema=None,
    )
    op.drop_index("ix_incidents_tenant_severity", table_name="incidents")
    op.create_index(
        "ix_incidents_tenant_severity",
        "incidents",
        ["tenant_id", "severity"],
        unique=False,
    )
    op.create_index(
        "uq_incidents_tenant_fingerprint_active",
        "incidents",
        ["tenant_id", "fingerprint"],
        unique=True,
        postgresql_where="((status)::text <> 'resolved'::text)",
    )
    op.alter_column(
        "incidents",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Last modification timestamp (server-side).",
        existing_comment="Last modification timestamp.",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "incidents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Row creation timestamp (server-side).",
        existing_comment="Row creation timestamp.",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "incidents",
        "resolved_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when status transitioned to resolved. NULL if open.",
        existing_comment="Timestamp when status was set to resolved. Null if still open.",
        existing_nullable=True,
    )
    op.alter_column(
        "incidents",
        "source_log_id",
        existing_type=sa.UUID(),
        comment="incident_id from ingested_log_metadata that triggered this incident. Provides traceability back to the original ingest event.",
        existing_comment="incident_id from ingested_log_metadata that triggered this incident. Provides a link back to the original ingest event.",
        existing_nullable=True,
    )
    op.alter_column(
        "incidents",
        "is_draft",
        existing_type=sa.BOOLEAN(),
        comment="True when confidence_score is below the tenant threshold. Draft incidents are stored but not published to Kafka.",
        existing_comment="True when confidence_score < tenant threshold. Draft incidents are stored but not published to Kafka.",
        existing_nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "incidents",
        "status",
        existing_type=sa.VARCHAR(length=32),
        comment="Incident lifecycle status: open | investigating | resolved | draft | duplicate.",
        existing_comment="Incident lifecycle status: open | investigating | resolved | closed | draft | duplicate.",
        existing_nullable=False,
        existing_server_default=sa.text("'open'::character varying"),
    )
    op.alter_column(
        "incidents",
        "error_message",
        existing_type=sa.TEXT(),
        comment="Full error message string from the triggering log entry.",
        existing_comment="Full error message string from the log entry.",
        existing_nullable=True,
    )
    op.alter_column(
        "incidents",
        "occurrences",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        comment="S3 object keys for all context buffers belonging to this incident. Format: logs/{tenant_id}/context/{incident_id}.json.gz",
        existing_comment="S3 keys of all compressed context buffers for this incident. Format: logs/{tenant_id}/context/{incident_id}.json.gz",
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::text[]"),
    )
    op.alter_column(
        "incidents",
        "occurrence_count",
        existing_type=sa.INTEGER(),
        comment="Total number of times this fingerprint has been observed.",
        existing_comment="Total number of times this fingerprint has been seen.",
        existing_nullable=False,
        existing_server_default=sa.text("1"),
    )
    op.drop_column("incidents", "assigned_user_ids")
    op.drop_table_comment(
        "analyses",
        existing_comment="Phase 4 — LangGraph agent execution traces.",
        schema=None,
    )
    op.alter_column(
        "analyses",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        comment="Timestamp when this analysis record was persisted.",
        existing_comment="Timestamp when this analysis was persisted.",
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "analyses",
        "matched_playbook_id",
        existing_type=sa.UUID(),
        comment="UUID of the PlaybookSnapshot that matched this incident. NULL if no playbook pattern matched.",
        existing_comment="UUID of the PlaybookSnapshot that matched this incident. NULL if no playbook matched.",
        existing_nullable=True,
    )
    op.alter_column(
        "analyses",
        "code_context_snapshot",
        existing_type=sa.TEXT(),
        comment="The exact code snippet text assembled by the CodeRetriever and passed to GPT-4. Stored for audit and analysis replay.",
        existing_comment="The exact code snippet text assembled by the CodeRetriever and passed to GPT-4. Stored for audit and replay.",
        existing_nullable=True,
    )
    op.alter_column(
        "analyses",
        "node_results",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        comment="Per-node execution metadata keyed by node name. Keys: classifier, code_retriever, playbook_matcher, analyzer, fix_generator, confidence_scorer, action_decision.",
        existing_comment="Per-node execution metadata keyed by node name. Keys: classifier, code_retriever, playbook_matcher, analyzer, fix_generator, confidence_scorer, action_decision. Each value contains latency_ms and node-specific fields.",
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "analyses",
        "total_latency_ms",
        existing_type=sa.INTEGER(),
        comment="Wall-clock milliseconds from run_agent task start to DB commit.",
        existing_comment="Wall-clock ms from run_agent task start to DB commit.",
        existing_nullable=True,
    )
    op.alter_column(
        "analyses",
        "incident_id",
        existing_type=sa.UUID(),
        comment="FK to incidents.id. One analysis per incident (1-to-1).",
        existing_comment="FK to incidents.id. One analysis per incident.",
        existing_nullable=False,
    )
    op.drop_table_comment(
        "alerts",
        existing_comment="Phase 4 — Notification dispatch records.",
        schema=None,
    )
    op.alter_column(
        "alerts",
        "failure_reason",
        existing_type=sa.TEXT(),
        comment="Error message populated when status=failed.",
        existing_comment="Error message if status=failed.",
        existing_nullable=True,
    )
    op.alter_column(
        "alerts",
        "recipient_user_id",
        existing_type=sa.UUID(),
        comment="UUID of the recipient user.",
        existing_comment="UUID of the recipient user (from alert_rule_snapshots.recipient_ids).",
        existing_nullable=True,
    )
    op.alter_column(
        "alerts",
        "alert_rule_id",
        existing_type=sa.UUID(),
        comment="UUID of the alert_rule_snapshot that triggered this alert. NULL if the alert was dispatched manually.",
        existing_comment="FK to alert_rule_snapshots.rule_id. NULL if alert was dispatched manually.",
        existing_nullable=True,
    )
    op.create_table(
        "playbook_embeddings",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("playbook_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.vector.VECTOR(dim=768),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("source_version", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "embedded_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["playbook_id"],
            ["playbook_snapshots.playbook_id"],
            name="fk_pb_playbook_snapshots",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="playbook_embeddings_pkey"),
        sa.UniqueConstraint("playbook_id", name="playbook_embeddings_playbook_id_key"),
    )
    op.create_index(
        "playbook_embeddings_tenant_id_source_version_idx",
        "playbook_embeddings",
        ["tenant_id", "source_version"],
        unique=False,
    )
    op.create_index(
        "playbook_embeddings_tenant_id_idx",
        "playbook_embeddings",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "playbook_embeddings_playbook_id_idx",
        "playbook_embeddings",
        ["playbook_id"],
        unique=False,
    )
    op.create_index(
        "playbook_embeddings_hnsw_idx",
        "playbook_embeddings",
        ["embedding"],
        unique=False,
        postgresql_with={"m": "16", "ef_construction": "128"},
        postgresql_using="hnsw",
    )
    # ### end Alembic commands ###
