"""add_pr_title_and_error

Revision ID: 2badda936ecb
Revises: b2c3d4e5f6a7
Create Date: 2026-06-26 06:40:58.149019+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2badda936ecb'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('pr_title', sa.Text(), nullable=True, comment='GitHub PR Title.'))
    op.add_column('incidents', sa.Column('pr_error', sa.Text(), nullable=True, comment='GitHub PR creation error or failure reason.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'pr_error')
    op.drop_column('incidents', 'pr_title')
    # ### end Alembic commands ###
