# Generated by Django 5.2.14 on 2026-05-23 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=256)),
                ('key', models.CharField(max_length=256)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'outbox',
                'indexes': [models.Index(fields=['published', 'created_at'], name='outbox_publish_eda034_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessedEvent',
            fields=[
                ('event_id', models.UUIDField(primary_key=True, serialize=False)),
                ('consumer_group', models.CharField(max_length=128)),
                ('topic', models.CharField(max_length=256)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'processed_events',
                'indexes': [models.Index(fields=['consumer_group', 'topic'], name='processed_e_consume_cb0d69_idx')],
            },
        ),
    ]
