# Generated by Django 5.2.14 on 2026-06-24 07:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0005_alter_tenant_plan_tier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_id', models.UUIDField(db_index=True, help_text='Matches incidents.id in DB-2 / IncidentSnapshot.incident_id in DB-1.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_threads', to='tenants.tenant')),
            ],
            options={
                'db_table': 'incident_threads',
            },
        ),
        migrations.CreateModel(
            name='ThreadMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Plain-text message body. Preserves line breaks.')),
                ('is_system_message', models.BooleanField(default=False, help_text='True for automated messages (status changes, assignments, AI events). System messages have author=None and a distinct visual style in the UI.')),
                ('is_deleted', models.BooleanField(default=False, help_text="Soft delete flag. Deleted messages render as 'This message was deleted' in the UI. The row is never physically removed.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_messages', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Set when this message is a reply to another message.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='collaboration.threadmessage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='collaboration.incidentthread')),
            ],
            options={
                'db_table': 'thread_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incidentthread',
            index=models.Index(fields=['tenant', 'incident_id'], name='cth_tenant_incident_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incidentthread',
            unique_together={('tenant', 'incident_id')},
        ),
        migrations.AddIndex(
            model_name='threadmessage',
            index=models.Index(fields=['thread', 'created_at'], name='cmsg_thread_created_idx'),
        ),
        migrations.AddIndex(
            model_name='threadmessage',
            index=models.Index(fields=['thread', 'parent'], name='cmsg_thread_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='threadmessage',
            index=models.Index(fields=['tenant', 'created_at'], name='cmsg_tenant_created_idx'),
        ),
    ]
