# Generated by Django 5.2.14 on 2026-06-24 11:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0001_initial"),
        ("tenants", "0005_alter_tenant_plan_tier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentStatusTransition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "incident_id",
                    models.UUIDField(
                        db_index=True, help_text="Matches incidents.id in DB-2."
                    ),
                ),
                ("from_status", models.CharField(max_length=32)),
                ("to_status", models.CharField(max_length=32)),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Optional explanation for the status change.",
                        max_length=280,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who made the status change.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_transitions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "incident_status_transitions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "incident_id"],
                        name="incident_st_tenant__6bd72b_idx",
                    )
                ],
            },
        ),
    ]
