# Generated by Django 5.2.14 on 2026-06-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0002_incidentstatustransition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incidentstatustransition",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional explanation for the status change.",
                max_length=280,
                null=True,
            ),
        ),
    ]
