"""
fastapi/app/schemas/parse_log.py

Pydantic schemas for the parse_log Celery task.

ParsedLogEvent is the typed, serialisable result object produced by
parse_log and consumed by run_agent. It is passed between tasks as
a JSON-serialised dict (not as a Python object reference) to ensure
it survives Celery serialisation cleanly.

Using a Pydantic model (rather than a plain dataclass) gives us:
  - Automatic type coercion on deserialization
  - Clear field documentation
  - JSON schema generation for API documentation
  - Validation on both construction and from_dict()
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, Field, field_validator, model_validator


class StackFrame(BaseModel):
    """
    A single frame extracted from a stack trace.

    All fields are Optional to handle partial stack traces gracefully.
    The parse_log task does best-effort extraction; downstream nodes
    (CodeRetriever) skip frames with missing file or line data.
    """

    file: str = Field(
        default="",
        description=(
            "Relative file path within the repository, "
            "e.g. src/payment/ChargeService.java"
        ),
    )
    line: int = Field(
        default=0,
        ge=0,
        description="1-based line number. 0 if not parseable.",
    )
    method: str = Field(
        default="",
        description=(
            "Fully-qualified method name, "
            "e.g. com.neuralops.payment.ChargeService.charge"
        ),
    )
    module: str = Field(
        default="",
        description="Module or package name. Empty string if not available.",
    )

    @field_validator("line", mode="before")
    @classmethod
    def coerce_line_to_int(cls, v: Any) -> int:
        """Coerce string line numbers from regex extraction to int."""
        try:
            return int(v)
        except (TypeError, ValueError):
            return 0


class ParsedLogEvent(BaseModel):
    """
    Structured output of the parse_log Celery task.

    This object is produced by parse_log and consumed by run_agent.
    It travels between tasks as a JSON dict via Celery's broker
    (Redis db 2). All fields must be JSON-serialisable.

    The incident_id field is the UUID of the original ingested_log_metadata
    row (generated by the ingest endpoint). It is NOT the ID of the
    Incident row that run_agent will create — that ID is generated fresh
    by run_agent.
    """

    # ── Routing context ───────────────────────────────────────────────────────
    tenant_id: str = Field(
        ...,
        description="Tenant UUID string (not UUID object for JSON compatibility).",
    )
    incident_id: str = Field(
        ...,
        description=(
            "UUID string of the ingested_log_metadata row that triggered "
            "this parse task. Used as source_log_id on the resulting Incident."
        ),
    )
    s3_path: str = Field(
        ...,
        description=(
            "S3 object key of the compressed context buffer. "
            "Format: logs/{tenant_id}/context/{incident_id}.json.gz"
        ),
    )

    # ── Service metadata ──────────────────────────────────────────────────────
    service_name: str = Field(
        ...,
        min_length=1,
        max_length=255,
        description="Name of the originating service.",
    )
    environment: str = Field(
        ...,
        min_length=1,
        max_length=64,
        description="Deployment environment label, e.g. production.",
    )

    # ── Extracted error data ──────────────────────────────────────────────────
    error_type: str = Field(
        default="UnknownError",
        max_length=255,
        description=(
            "Exception or error class name extracted from the log message. "
            "e.g. NullPointerException, ValueError, DatabaseError."
        ),
    )
    error_message: str = Field(
        default="",
        description=(
            "Full error message string from the highest-severity log entry "
            "in the context buffer."
        ),
    )
    severity: str = Field(
        default="unknown",
        description="Severity level: critical | error | warning | info | debug | unknown.",
    )

    # ── Crash location ────────────────────────────────────────────────────────
    crash_file: str = Field(
        default="",
        description=(
            "File path from the top frame of the stack trace. "
            "Empty if no stack trace was parseable."
        ),
    )
    crash_line: int = Field(
        default=0,
        ge=0,
        description=(
            "Line number from the top frame of the stack trace. " "0 if not parseable."
        ),
    )
    crash_method: str = Field(
        default="",
        description=(
            "Method name from the top frame of the stack trace. "
            "Empty if not parseable."
        ),
    )

    # ── Full stack trace ──────────────────────────────────────────────────────
    stack_frames: List[StackFrame] = Field(
        default_factory=list,
        description=(
            "Ordered list of stack frames from the triggering log entry. "
            "Index 0 is the innermost (crash) frame. "
            "Maximum 20 frames stored; deeper frames are truncated."
        ),
    )

    # ── Context buffer metadata ───────────────────────────────────────────────
    context_log_count: int = Field(
        default=0,
        ge=0,
        description="Number of log entries in the context buffer fetched from S3.",
    )

    @field_validator("severity", mode="before")
    @classmethod
    def normalise_severity(cls, v: Any) -> str:
        """Map common severity strings to the canonical set."""
        if not isinstance(v, str):
            return "unknown"
        mapping = {
            "critical": "critical",
            "fatal": "critical",
            "error": "error",
            "err": "error",
            "warning": "warning",
            "warn": "warning",
            "info": "info",
            "information": "info",
            "debug": "debug",
            "trace": "debug",
        }
        return mapping.get(v.lower(), "unknown")

    @field_validator("stack_frames", mode="before")
    @classmethod
    def cap_stack_frames(cls, v: Any) -> List[Any]:
        """Cap stack frames at 20 to keep the payload bounded."""
        if isinstance(v, list):
            return v[:20]
        return []

    def to_dict(self) -> Dict[str, Any]:
        """
        Serialise to a plain JSON-compatible dict for Celery task arguments.

        Converts StackFrame objects to dicts and ensures all values are
        JSON-serialisable primitives.
        """
        return {
            "tenant_id": self.tenant_id,
            "incident_id": self.incident_id,
            "s3_path": self.s3_path,
            "service_name": self.service_name,
            "environment": self.environment,
            "error_type": self.error_type,
            "error_message": self.error_message,
            "severity": self.severity,
            "crash_file": self.crash_file,
            "crash_line": self.crash_line,
            "crash_method": self.crash_method,
            "stack_frames": [frame.model_dump() for frame in self.stack_frames],
            "context_log_count": self.context_log_count,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ParsedLogEvent":
        """
        Deserialise from a Celery task argument dict.

        Validates all fields via Pydantic on construction,
        raising ValidationError on invalid input.
        """
        return cls.model_validate(data)
