# Generated by Django 5.2.14 on 2026-05-21 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_tenantconfiguration_tenant_conf_tenant__216c25_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentSnapshot',
            fields=[
                ('incident_id', models.UUIDField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32)),
                ('severity', models.CharField(max_length=32)),
                ('confidence_score', models.FloatField(null=True)),
                ('error_type', models.CharField(blank=True, max_length=255)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('assigned_user_id', models.UUIDField(blank=True, null=True)),
                ('source_version', models.BigIntegerField(default=0)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'incident_snapshots',
                'indexes': [models.Index(fields=['tenant', 'status'], name='incident_sn_tenant__ec503c_idx'), models.Index(fields=['tenant', 'created_at'], name='incident_sn_tenant__122c3a_idx')],
            },
        ),
    ]
