# Generated by Django 5.2.14 on 2026-06-11 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_extend_incident_snapshot_phase4"),
        ("tenants", "0003_tenantconfiguration_tenant_conf_tenant__216c25_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incidentsnapshot",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameIndex(
            model_name="incidentsnapshot",
            new_name="incident_sn_tenant_status_idx",
            old_name="incident_sn_tenant__ec503c_idx",
        ),
        migrations.RenameIndex(
            model_name="incidentsnapshot",
            new_name="incident_sn_tenant_created_idx",
            old_name="incident_sn_tenant__122c3a_idx",
        ),
        migrations.AlterField(
            model_name="incidentsnapshot",
            name="assigned_user_id",
            field=models.UUIDField(
                blank=True,
                help_text="UUID of the assigned engineer (from DB-2).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incidentsnapshot",
            name="confidence_score",
            field=models.FloatField(
                blank=True,
                help_text="Agent confidence score in range [0.0, 1.0].",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="incidentsnapshot",
            name="created_at",
            field=models.DateTimeField(
                help_text="Incident creation timestamp from FastAPI DB-2."
            ),
        ),
        migrations.AlterField(
            model_name="incidentsnapshot",
            name="error_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Exception or error class name.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="incidentsnapshot",
            name="incident_id",
            field=models.UUIDField(
                editable=False,
                help_text="UUID matching incidents.id in DB-2. Set by the Kafka consumer; never auto-generated.",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="incidentsnapshot",
            name="service_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of the originating service.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="incidentsnapshot",
            name="severity",
            field=models.CharField(
                default="unknown",
                help_text="critical | high | medium | low | info | unknown.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="incidentsnapshot",
            name="source_version",
            field=models.BigIntegerField(
                default=0,
                help_text="Monotonically increasing version counter from the source incident. Used to reject stale Kafka redeliveries.",
            ),
        ),
        migrations.AlterField(
            model_name="incidentsnapshot",
            name="status",
            field=models.CharField(
                db_index=True,
                default="open",
                help_text="open | investigating | resolved | draft | duplicate.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="incidentsnapshot",
            name="synced_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of the last successful snapshot upsert by the consumer.",
            ),
        ),
        migrations.AlterField(
            model_name="incidentsnapshot",
            name="tenant",
            field=models.ForeignKey(
                help_text="Owning tenant.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incident_snapshots",
                to="tenants.tenant",
            ),
        ),
    ]
