[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --cov=users --cov=tenants --cov-report=html --cov-report=term-missing --strict-markers
testpaths = .
markers =
    django_db: mark test as a database test
    slow: mark test as slow
    auth: authentication tests
    oauth: OAuth tests
    invitation: invitation tests