# Generated by Django 5.2.14 on 2026-05-23 06:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0003_tenantconfiguration_tenant_conf_tenant__216c25_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "confidence_threshold",
                    models.FloatField(
                        default=0.7,
                        help_text="Minimum confidence score (0.0–1.0) to trigger this alert.",
                    ),
                ),
                (
                    "severity_filter",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of severity levels, e.g. ["critical", "high"].',
                    ),
                ),
                (
                    "recipient_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of user UUIDs (as strings) who receive notifications.",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "source_version",
                    models.BigIntegerField(
                        default=1,
                        help_text="Auto-incremented on every save; used by snapshot consumers to reject stale events.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "alert_rules",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "enabled"],
                        name="alert_rules_tenant__31d225_idx",
                    )
                ],
            },
        ),
    ]
