# Generated by Django 5.2.14 on 2026-06-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_rls_policies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alertrule",
            name="recipient_ids",
        ),
        migrations.AddField(
            model_name="alertrule",
            name="destinations",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of destination objects (e.g. {'type': 'user', 'id': 'uuid'} or {'type': 'pagerduty', 'webhook_url': 'url'}).",
            ),
        ),
    ]
