# Generated by Django 5.2.14 on 2026-06-25 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("push", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pushdeliverylog",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="pushdeliverylog",
            name="token",
        ),
        migrations.DeleteModel(
            name="DeviceToken",
        ),
        migrations.DeleteModel(
            name="PushDeliveryLog",
        ),
    ]
