# Generated by Django 5.2.14 on 2026-05-21 14:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_user_id', models.UUIDField()),
                ('action', models.CharField(choices=[('tenant_suspended', 'Tenant Suspended'), ('tenant_reinstated', 'Tenant Reinstated'), ('tenant_viewed', 'Tenant Viewed')], max_length=50)),
                ('target_tenant_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'superadmin_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
